# Generated by Django 3.0.6 on 2021-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(default='Null', max_length=100, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(default='Null', max_length=100, verbose_name='password')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
