# Generated by Django 3.0.6 on 2021-06-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem_name', models.CharField(default='', max_length=50, verbose_name='poem_name')),
                ('theme', models.CharField(default='', max_length=50, verbose_name='theme')),
            ],
        ),
    ]
