# Generated by Django 3.0.6 on 2021-06-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoeticChina', '0002_auto_20210603_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='content',
            field=models.TextField(default=' ', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='introduction',
            field=models.TextField(default=' ', verbose_name='intro'),
        ),
    ]
