# Generated by Django 3.0.6 on 2021-06-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoeticChina', '0003_auto_20210603_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='poet_id',
            new_name='poet',
        ),
    ]
