# Generated by Django 3.0.6 on 2021-06-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoeticChina', '0005_auto_20210603_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, verbose_name='username')),
                ('password', models.CharField(default='', max_length=100, verbose_name='password')),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
