# Generated by Django 3.0.6 on 2021-06-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoeticChina', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
