# Generated by Django 3.0.6 on 2021-06-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PoeticChina', '0007_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='theme',
        ),
        migrations.AddField(
            model_name='poem',
            name='analysis',
            field=models.TextField(default='', verbose_name='analysis'),
        ),
        migrations.CreateModel(
            name='Poem_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='未分类', max_length=50, verbose_name='theme')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PoeticChina.Poem')),
            ],
            options={
                'db_table': 'poem_theme',
                'unique_together': {('poem_id', 'theme')},
            },
        ),
    ]
