# Generated by Django 3.0.6 on 2021-07-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoeticChina', '0009_poem_poem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='time',
            field=models.CharField(default='$tang$', max_length=10, verbose_name='time'),
        ),
    ]
