# Generated by Django 3.0.6 on 2021-07-03 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('PoeticChina', '0011_poet_poet_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PoeticChina.Poem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Login')),
            ],
        ),
    ]
