# Generated by Django 3.0.6 on 2021-07-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoeticChina', '0012_collect'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collect',
            table='collect',
        ),
    ]
